# Generated by Django 4.1.7 on 2023-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inflable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
            ],
        ),
    ]
