# Generated by Django 4.1.7 on 2023-03-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InflablesApp', '0003_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_elemento',
        ),
    ]
