# Generated by Django 4.1.7 on 2023-03-25 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UsersApp', '0003_rename_imagen_avatar_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Perfil',
        ),
    ]
