# Generated by Django 4.1.7 on 2023-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_rename_perfil_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
